name: Automatic CLI Docs Update

on:
  pull_request:
    branches: ["doc-226-target-test"]
    types: [converted_to_draft]
env:
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  trigger-cli-docs-update:
    name: Trigger CLI Docs Update
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CLI Docs Update workflow in vcluster-docs
        run: |
          gh api \
          --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/loft-sh/vcluster-docs/dispatches \
            -f "event_type=update-cli-docs" \
            -F "client_payload[ref]={{ github.event.pull_request.head.ref }}" \
            -F "client_payload[title]={{ github.event.pull_request.title }}" \
            -F "client_payload[version]=some-version"
