name: Automatic CLI Docs Update

on:
  pull_request:
    branches: ["doc-226-target-test"]
    types: [opened, reopened, edited, ready_for_review, converted_to_draft]

jobs:
  trigger-cli-docs-update:
    name: Trigger CLI Docs Update
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cli-docs workflow
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = 'from pr ${{ github.event.pull_request.number }}'
            const version = 'some-version';
            const ref = '${{ github.event.pull_request.head.sha }}';
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: 'loft-sh',
              repo: 'vcluster-docs',
              workflow_id: 'cli-docs.yaml',
              ref: 'main',
              inputs: {
                version: version,
                ref: ref,
                title: title,
              }
            });
            console.log(response)
