apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
spec:
  replicas: 10
  selector:
    app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: nginx:latest
